# Generated by Django 6.0.4 on 2026-04-08 20:47

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Plan',
            },
        ),
        migrations.CreateModel(
            name='UserFirstUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(message='promocode must be 6–12 characters long and contain only uppercase letters and digits', regex='^[A-Z0-9]{6,12}$')])),
                ('bonus_type', models.CharField(choices=[('percent_discount', 'Percent Discount'), ('amount_discount', 'Amount Discount'), ('days', 'Days'), ('balance', 'Balance')], max_length=32)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(db_default=True)),
                ('active_from', models.DateTimeField()),
                ('active_to', models.DateTimeField()),
                ('activations_count', models.PositiveIntegerField(db_default=0, editable=False)),
                ('max_activations', models.PositiveIntegerField(blank=True, null=True)),
                ('max_user_activations', models.PositiveIntegerField(blank=True, null=True)),
                ('personal_for_user_id', models.UUIDField(blank=True, null=True)),
                ('is_for_new_users', models.BooleanField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('plans', models.ManyToManyField(blank=True, related_name='promocodes', to='service.plan')),
            ],
            options={
                'verbose_name': 'Promocode',
            },
        ),
        migrations.CreateModel(
            name='PromocodeActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('created_at', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_activations', to='service.plan')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='service.promocode')),
            ],
            options={
                'verbose_name': 'Promocode activation',
            },
        ),
        migrations.CreateModel(
            name='UserPromocodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('activations_count', models.PositiveIntegerField(db_default=0, editable=False)),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.promocode')),
            ],
            options={
                'unique_together': {('promocode', 'user_id')},
            },
        ),
    ]
